// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnN8mLqPwHp7IPonEGWo3k6O-POaykKoA',
    appId: '1:479869545705:web:c4eacfe2aed718ccec1478',
    messagingSenderId: '479869545705',
    projectId: 'chatapp-0270',
    authDomain: 'chatapp-0270.firebaseapp.com',
    storageBucket: 'chatapp-0270.appspot.com',
    measurementId: 'G-TMZL79FR3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9n_43hxQ_6J4oq2GmKIr8lB6Shj8XAJQ',
    appId: '1:479869545705:android:cfd3a29ead85da01ec1478',
    messagingSenderId: '479869545705',
    projectId: 'chatapp-0270',
    storageBucket: 'chatapp-0270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6t87nQbcMKZ97sB4MiXDf9-4d6lqpbqI',
    appId: '1:479869545705:ios:bfc31b6eac47dd91ec1478',
    messagingSenderId: '479869545705',
    projectId: 'chatapp-0270',
    storageBucket: 'chatapp-0270.appspot.com',
    iosClientId:
        '479869545705-i4p2gq7r7cr4r7u4dtvk8fgmkln7lvn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );
}
